repos:
    - repo: https://github.com/RobertCraigie/pyright-python
      rev: v1.1.411
      hooks:
          - id: pyright

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.15.16
      hooks:
          - id: ruff-format
          - id: ruff-check
            args: ["--fix"]
