name: Test

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - main
            - develop

jobs:
    code_qa:
        name: Code quality assurance testing

        runs-on: ubuntu-latest

        steps:
            - name: Doing checkout
              uses: actions/checkout@v6

            - name: Setting up Python
              uses: actions/setup-python@v6
              with:
                  python-version: 3.12

            - name: Installing dependencies
              run: |
                  pip install uv
                  uv export -o requirements.txt
                  pip install -r requirements.txt

            - name: Validating typing
              run: uv run poe types

            - name: Validating formatting
              run: uv run poe check
